version: "3.8"

networks:
  assignment04:
    driver: bridge

services:
  # Streamlit service for your Streamlit application
  streamlit:
    build:
      context: ./streamlit
      dockerfile: ./dockerfile
    ports:
      - "8503:8503"
    volumes:
      - ./streamlit:/streamlit
      - ~/.aws:/root/.aws:ro
    networks:
      - assignment04

  # FastAPI service for your FastAPI application
  fastapi:
    build:
      context: ./fastapi
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/fastapi
    networks:
      - assignment04

  # Airflow service for your Apache Airflow instance
  airflow:
    build:
      context: ./airflow
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False  # Disable loading of example DAGs
    volumes:
      - ./airflow/dags:/opt/airflow/dags  # Mount existing DAGs directory
      - ./airflow/logs:/opt/airflow/logs  # Mount existing logs directory
      - ./airflow/plugins:/opt/airflow/plugins  # Mount existing plugins directory
    user: "0:0"
    networks:
      - assignment04
